spring:
  profiles:
    active: local
---
spring:
  profiles: local
  kafka:
    templete:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
       bootstrap.servers: localhost:9092,localhost:9093,localhost:9094

---
spring:
  profiles: dev
  kafka:
    producer:
      bootstrap-servers: dev:9092,dev:9093,dev:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


---
spring:
  profiles: test
  kafka:
    producer:
      bootstrap-servers: test:9092,test:9093,test:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


---
spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers: prod:9092,prod:9093,prod:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer